#!/usr/bin/expect

# run craft setup script
spawn /srv/www/craft setup

# use environment variables to connect to db container
expect {
  "Which database driver are you using?" { send "mysql\n"; exp_continue; }
  "Database server name or IP address:" { send "$env(DB_PORT_3306_TCP_ADDR)\n"; exp_continue; }
  "Database port:" { send "$env(DB_PORT_3306_TCP_PORT)\n"; exp_continue; }
  "Database username:" { send "$env(DB_ENV_MYSQL_USER)\n"; exp_continue; }
  "Database password:" { send "$env(DB_ENV_MYSQL_PASSWORD)\n"; exp_continue; }
  "Database name:" { send "$env(DB_ENV_MYSQL_DATABASE)\n"; exp_continue; }
  "Database table prefix:" { send "\n"; exp_continue; }

  "Install Craft now?" { send "yes\n"; exp_continue; }
  "Username:" { send "$env(CRAFT_USER)\n"; exp_continue; }
  "Email:" { send "$env(CRAFT_EMAIL)\n"; exp_continue; }
  "Password:" { send "$env(CRAFT_PASSWORD)\n"; exp_continue; }
  "Confirm:" { send "$env(CRAFT_PASSWORD)\n"; exp_continue; }
  "Site name:" { send "$env(CRAFT_SITE_NAME)\n"; exp_continue; }
  "Site URL:" { send "$env(CRAFT_SITE_URL)\n"; exp_continue; }
  "Site language:" { send "\n"; exp_continue; }
}

expect eof
